# Generated by Django 5.0.1 on 2024-01-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('food_company_name', models.CharField(choices=[('SWIGGY', 'SWIGGY'), ('ZOMATO', 'ZOMATO')], max_length=100)),
            ],
        ),
    ]
