# Generated by Django 5.0.1 on 2024-01-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiggySessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=100)),
                ('t_id', models.CharField(max_length=100)),
                ('s_id', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED')], max_length=100)),
            ],
        ),
    ]
