# Generated by Django 5.0.1 on 2024-01-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_swiggysessiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiggysessiondata',
            name='session_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
